openapi: 3.0.3

info:
  title: URL Shortener API
  version: 1.0.0

servers:
- description: "Optional server description, e.g. Main (production) server"
  url: http://localhost:8089/v1

paths:

  /shorten:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_shorten_post_request"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_shorten_post_201_response"
          description: Created
      summary: Create a short URL

  /{short_code}:
    get:
      parameters:
      - explode: false
        in: path
        name: short_code
        required: true
        schema:
          type: string
        style: simple
      responses:
        "302":
          description: Redirection to long URL
        "404":
          description: URL not found
      summary: Redirect to the original URL

components:
  schemas:
    
    _shorten_post_request:
      $ref: "./schemas/shorten-post-request.yaml"
    
    _shorten_post_201_response:
      $ref: "./schemas/shorten-post-201-response.yaml"
