package constants

const (
	URL_SHORTENER_SERVICE   = "URL_SHORTENER_SERVICE"
	PUBLIC_BASE_URL         = "PUBLIC_BASE_URL"
	MONGODB_COLLECTION_NAME = "MONGODB_COLLECTION_NAME"
	MONGODB_DATABASE_NAME   = "MONGODB_DATABASE_NAME"
)
